export enum GetPokemonActions {
    GETPOKEMON_DEFAULT = "GETPOKEMON_DEFAULT",
    GETPOKEMON_STARTED = "GETPOKEMON_STARTED",
    GETPOKEMON_SUCCESSFUL = "GETPOKEMON_SUCCESSFUL",
    GETPOKEMON_FAILED = "GETPOKEMON_FAILED"
}